### ISSUE TITLE
Screen sleeping after a while

### ISSUE THREAD

**Issue by cburza** [abacao/Boot2Kodi#7]
Hey, do you perhaps know how to prevent the screen from sleeping? I do not have this configured within Kodi, so I suspect it might be something to do with the X11 config?

**Comment by abacao** [comment]
Hello,
Can you provide more information?
What OS are you using and version?
Did you follow the instructions?

**Comment by cburza** [comment]
@abacao I am using Ubuntu 18.04 server edition. The installation did not have X11 installed. Just used your script as per the instructions.

**Comment by abacao** [comment]
@cburza wasn't able to reproduce your issue. Are you installing it on a battery-powered computer? Are you sure that is the system that is putting the display to sleep and not the monitor itself?

**Comment by cburza** [comment]
@abacao No it is a normal desk machine. No the TV never switches off. I have a Chromecast connected to it and do not have issues with it. It might be some other non standard configuration on the server that I am not aware of. I will close the issue for now as it seems it is not related to normal behaviour when installing from scratch.

**Comment by Waliers** [comment]
I have the same issue. Did anyone found a workarround? I used a fresh install of Ubuntu 18.04 and run this script. After 10 minutes of doing nothing the screen falls a sleep. This doesn't happen when watching something. I can still access through SSH so I just reboot the PC and it works again but it would be nice if it didn't turn of the TV after 10 mins. It's connected to a normal PC through HDMI. Since I still can connect with SSH i'm sure its not the PC that turns itself off.

**Comment by abacao** [comment]
Hello,
Have you checked [this](https://kodi.wiki/view/Settings/System/Power_saving) ?

**Comment by Waliers** [comment]
yes I did. Default it's off in code. However I noticed it's a setting in Ubuntu.

When I run `DISPLAY=:0 xset -q`

The output is:
`
DPMS (Energy Star):
  Standby: 600    Suspend: 600    Off: 600
  DPMS is Enabled
`
Disabling DPMS or setting the settings to a high treshold seem to be solving the issue.

**Comment by cburza** [comment]
@Waliers Did you find a solution to the issue. I have tried turning DPMS off in the `xorg.conf` file as well as `.xinitrc`.

**Comment by Waliers** [comment]
Hi @cburza, I added `xset -display 0:0 -dpms s off` to `/usr/bin/kodi-standalone` at the the line below `#!/bin/bash`

I also made `.xinitrc` have 
`# Power savings off
xset -dpms s off`

And made a `/etc/X11/xorg.conf` with 
`Section "ServerFlags"
    Option        "BlankTime"          "0"  # Blank the screen (Fake)
    Option        "StandbyTime"        "0"  # Turn off screen (DPMS)
    Option        "SuspendTime"        "0"
    Option        "OffTime"            "0"
EndSection`

An easier solution might be to add `xset s 0 s blank -dpms &` to the autostart but since it's working now and I don't have the time to test further I decided to leave it like this.

**Comment by radusuciu** [comment]
Also having this same exact issue. Trying some of these fixes and will report back.

**Comment by radusuciu** [comment]
Alright, the following did nothing to affect the DPMS setting that is reported by `DISPLAY=:0 xset -q`:

- `xset -dpms s off` in `/home/kodi/.xinitrc`
- `xset -dpms s off` in `/etc/X11/xinit/xinitrc`
- `xset -display 0:0 -dpms s off` at top of `/usr/bin/kodi-standalone` file

However, creating `/etc/X11/xorg.conf` with the following contents did affect the times being reported by `DISPLAY=:0 xset -q`, though still not the DPMS status:

```
Section "ServerFlags"
        Option  "Xinerama"      "0"
        Option  "BlankTime"     "0"  # Blank the screen (Fake)
        Option  "StandbyTime"   "0"  # Turn off screen (DPMS)
        Option  "SuspendTime"   "0"
        Option  "OffTime"       "0"
EndSection```

It seems like setting the DPMS thresholds to 0 is sufficient to avoid this issue.

thanks @Waliers, and also P.Kosunen from the kodi forums: https://forum.kodi.tv/showthread.php?tid=334186
